//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Stock.Models
{
    
    
    public partial class produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produto()
        {
            this.entrada_produto = new HashSet<entrada_produto>();
            this.inventario_estoque = new HashSet<inventario_estoque>();
            this.saida_produto = new HashSet<saida_produto>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public string nome { get; set; }
        public decimal preco_custo { get; set; }
        public decimal preco_venda { get; set; }
        public int quant_estoque { get; set; }
        public int id_unidade_medida { get; set; }
        public int id_grupo { get; set; }
        public int id_marca { get; set; }
        public int id_fornecedor { get; set; }
        public int id_local_armazenamento { get; set; }
        public bool ativo { get; set; }
        public string imagem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrada_produto> entrada_produto { get; set; }
        public virtual fornecedor fornecedor { get; set; }
        public virtual grupo_produto grupo_produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventario_estoque> inventario_estoque { get; set; }
        public virtual local_armazenamento local_armazenamento { get; set; }
        public virtual marca_produto marca_produto { get; set; }
        public virtual unidade_medida unidade_medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saida_produto> saida_produto { get; set; }
    }
}
